export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE'


export const ADD_CUSTOMERS_START = 'ADD_CUSTOMERS_START'
export const ADD_CUSTOMERS_SUCCESS = 'ADD_CUSTOMERS_SUCCESS'
export const ADD_CUSTOMERS_FAILURE = 'ADD_CUSTOMERS_FAILURE'


export const FETCH_PHONE_BY_ID_START = 'FETCH_PHONE_BY_ID_START'
export const FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCESS'
export const FETCH_PHONE_BY_ID_FAILURE = 'FETCH_PHONE_BY_ID_FAILURE'


export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET'


export const SEARCH_PHONE = 'SEARCH_PHONE'